# Generated by Django 4.2.5 on 2023-09-14 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empno', models.IntegerField()),
                ('ename', models.CharField(max_length=40)),
                ('sal', models.IntegerField()),
                ('deptno', models.IntegerField()),
            ],
        ),
    ]
