# Generated by Django 4.2.5 on 2023-09-14 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyFirstApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petname', models.CharField(max_length=50)),
                ('petcolor', models.CharField(max_length=30)),
                ('petage', models.IntegerField()),
            ],
        ),
    ]
